CUNY Math with Python Bridge HW2

In [166]:
import numpy as np
from sympy import Poly, Symbol
import sympy as sp
from numpy.linalg import pinv
from matplotlib import pyplot

1.  Write a Python program to compute the eigenvalues and right eigenvectors of a given square array.

In [64]:
def calc_eig_val(matrix_a):
    lamda = Symbol('lamda')
    p = sp.Matrix(matrix_a).charpoly(lamda)
    return np.roots(p.all_coeffs())

In [153]:
def calc_eig_vec(eig_val,mat):
    right = eig_val*np.eye(len(mat))
    return np.linalg.solve(mat,right)

In [120]:
#better notation convention on matrix
z = np.matrix('1 2 3;4 5 6;5 6 7',dtype=float)
z
z2 = np.matrix('1 2 ;4 5',dtype=float)
z2

matrix([[1., 2.],
        [4., 5.]])

In [162]:
eig2 = calc_eig_val(z)
eig2

array([13.86545993, -0.86545993,  0.        ])

In [158]:
eig3 = calc_eig_val(z2)
eig3

array([ 6.46410162, -0.46410162])

I realize that my simplified eigenvector calculation is off, but I believe conceptually I am starting to understand 
how linear equations can be represented within matrices and how numpy allows you to solve for that. I need to further read about row reduction to understand why the solve in linalg is providing alternative eigenvector values although in theory the formula is setting up 𝐴𝑣= 𝜆𝐼𝑣

In [165]:
for eig in eig3:
    print(calc_eig_vec(eig,z2))

[[-10.77350269   4.30940108]
 [  8.61880215  -2.15470054]]
[[ 0.77350269 -0.30940108]
 [-0.61880215  0.15470054]]


In [161]:
z_eig_val, z_eig_vec = np.linalg.eig(z2)
print(z_eig_val)
print(z_eig_vec)

[-0.46410162  6.46410162]
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [61]:
e_vals2, e_vecs2 = np.linalg.eig(z)
print(e_vals2)
print(e_vecs2)

[ 1.38654599e+01 -8.65459931e-01  7.42011605e-16]
[[ 0.26830632  0.8780304   0.40824829]
 [ 0.62003176 -0.12665002 -0.81649658]
 [ 0.73727358 -0.46154349  0.40824829]]


In [17]:
#alternative testing for calculating eigenvalues; issue properly using rref formula and then properly assigning into a matrix
#based off of a matlab tutorial that I found online
eig_shape = (len(A),len(A))
eig_a = np.zeros(eig_shape)
for idx in range(0,len(A)):
    s_i = roots_a[idx]
    print(s_i)
    a_mod = (A - s_i *(np.eye(len(A))))
    print(a_mod)
    a_mod_ref = sp.Matrix(a_mod).rref()
    a_mod_red2 = np.array(a_mod_ref)
    print(a_mod_red2)#a_mod_red[0],'\n',len(A)-2)
    v_i = [-a_mod_red[0][0:len(A)-2,len(A)-1],1]
    print(v_i)
    v_i_mod = v_i/np.linalg.norm(v_i)
    eig_vec_manual[:,idx] = v_i_mod

14.470759141058467
[[-13.47075914   2.           3.        ]
 [  4.          -9.47075914   6.        ]
 [  7.           4.          -5.47075914]]
[Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]) (0, 1, 2)]
[Matrix([[0]]), 1]


TypeError: cannot add <class 'sympy.matrices.dense.MutableDenseMatrix'> and <class 'int'>

2.  Write a Python program to compute the factor of a given array by Singular Value Decomposition

X = U · Σ · V^T
Where A is the real m x n matrix that we wish to decompose, U is an m x m matrix, Sigma (often represented by the uppercase Greek letter Sigma) is an m x n diagonal matrix, and V^T is the  transpose of an n x n matrix where T is a superscript.

The matrices U, D and V can be found by transforming A in a square matrix and by computing the eigenvectors of this square matrix. The square matrix can be obtain by multiplying the matrix A by its transpose in one way or the other:

U corresponds to the eigenvectors of AAT
V corresponds to the eigenvectors of ATA
D corresponds to the eigenvalues AAT or ATA which are the same.

In [167]:
def manual_svd(a):
    D, U = np.linalg.eig(a.dot(a.T))
    _, V = np.linalg.eig(a.T.dot(a))
    print('u: \n',U)
    print('d: \n',np.sqrt(D[~np.isnan(D)]))
    print('v: \n',V)
    return U,D,V

In [168]:
in_arr = np.asarray([[1, 4],[2, 6]])
u_val, d_val, v_val = manual_svd(in_arr)
U,s,Vh = np.linalg.svd(in_arr)
print('\nu:',U,'\n\ns:',s,'\n\nvh:',Vh)

u: 
 [[-0.83800537 -0.54566198]
 [ 0.54566198 -0.83800537]]
d: 
 [0.26506989 7.54517978]
v: 
 [[-0.95566711 -0.29444928]
 [ 0.29444928 -0.95566711]]

u: [[-0.54566198 -0.83800537]
 [-0.83800537  0.54566198]] 

s: [7.54517978 0.26506989] 

vh: [[-0.29444928 -0.95566711]
 [ 0.95566711 -0.29444928]]


In [169]:
arr2 = np.asarray([[1, 4],[2, 3],[2,8]])
d, u = np.linalg.eig(arr2.dot(arr2.T))
_, v = np.linalg.eig(arr2.T.dot(arr2))
print('u: \n',u)
print('d: \n',np.sqrt(d[~np.isnan(d)]))
print('v: \n',v)

u: 
 [[ 4.18879369e-01  8.94427191e-01  1.56652720e-01]
 [ 3.50286130e-01 -4.26190563e-16 -9.36642743e-01]
 [ 8.37758737e-01 -4.47213595e-01  3.13305439e-01]]
d: 
 [9.83399419        nan 1.13690731]
v: 
 [[-0.95876056 -0.28421505]
 [ 0.28421505 -0.95876056]]


/Users/JoshForster/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in sqrt
  """


In [170]:
U,s,Vh = np.linalg.svd(arr2)
print('U: \n',U)
print('s: \n',s)
print('vh: \n',Vh)

U: 
 [[ 4.18879369e-01 -1.56652720e-01 -8.94427191e-01]
 [ 3.50286130e-01  9.36642743e-01  5.55111512e-17]
 [ 8.37758737e-01 -3.13305439e-01  4.47213595e-01]]
s: 
 [9.83399419 1.13690731]
vh: 
 [[ 0.28421505  0.95876056]
 [ 0.95876056 -0.28421505]]


3.  Write a Python program to compute the determinant of an array.

In [171]:
def calcMatMinor(mat,i,j):
    #create 2x2 matrix to carry out simplest matrix multiplication
    #pulls rows 1+ to return available 2,2 subsets of matrix
        
    return [r[:j] + r[j+1:] for r in (mat[:i]+mat[i+1:])]

def calcMatDeter(mat):
    #2x2 matrix determinant calc
    if len(mat) == 2:
        return mat[0][0]*mat[1][1]-mat[0][1]*mat[1][0]

    determinant = 0
    for col in range(len(mat)):
        determinant += ((-1)**col)*mat[0][col]*calcMatDeter(calcMatMinor(mat,0,col))
    return determinant

In [173]:
arr : np.array = ([[ 6, 1, 1],
[ 4, -2, 5],
[ 2, 8, 7]])
det_manual = calcMatDeter(arr)
det = np.linalg.det(arr) 
det_manual == det

True

In [175]:
t : np.array = ([(1, 2, 3,5), (4, 5, 6,2), (1, 2, 3,7), (4, 5, 6,8)])
det_manual2 = calcMatDeter(t)
det2 = np.linalg.det(t) 
det_manual2 == det2

True